### ISSUE TITLE
Search results are not legible

### ISSUE THREAD

**Issue by alexkvazos** [silofy/hackthebox#4]
When using CMD+F to find text in files the results in the sidebar are not legible. This is on the non lite version.

Example with HackTheBox
<img width="294" alt="Screen Shot 2020-08-24 at 11 49 08" src="https://user-images.githubusercontent.com/4448627/91073293-7412d080-e600-11ea-8341-167943270c70.png">

Example with Material Theme
<img width="234" alt="Screen Shot 2020-08-24 at 11 48 54" src="https://user-images.githubusercontent.com/4448627/91073304-7bd27500-e600-11ea-905b-73c84b972afe.png">

**Comment by brilang** [comment]
Does anyone have a fix for this? How can I change the highlight color for search results?

**Comment by Megha-Pathak** [comment]
I tried resolving this issue in this PR: https://github.com/silofy/hackthebox/pull/10

**Comment by silofy** [comment]
Fixed in 0.2.9, thanks for your help!
